import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'

const RobotoFont = Roboto({ subsets: ['latin'], weight: ['900'] })

export const metadata: Metadata = {
  title: 'DBMS Lab ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={RobotoFont.className}>{children}</body>
    </html>
  )
}
